### ISSUE TITLE
JAWS V1.0 Installation Guide

### ISSUE THREAD

**Issue by jwulf** [jaws-stack/JAWS#85]
Hi, I can't test or contribute for 1.0 at the moment because I have no idea how to install it. 

Can you throw some rough instructions in this issue? If you can I'll test and document them.

And I get that it may well change before 1.0 is baked, but this will allow me to get up to speed and we'll have some install docs evolving along with the code.

**Comment by tobyhede** [comment]
Second to this. I am lost, but would love to help.

**Comment by doapp-ryanp** [comment]
There is intentionally not any docs for the v1.0 branch because it is still a WIP.  We are working hard on getting it ready for beta and don't want to be spending time fielding issues on a feature branch that is changing rapidly.

With that said we are very close to beta.  Keep an eye on the [doc](https://docs.google.com/document/d/1SeTgtsQc620vcwgGMZ4F2yuWVf-A3JmpTn1VT8pKYsA/edit#) for progress (at the top).

Once we have a solid foundation we will open it up for pull requests and of will have good docs.

**Comment by ac360** [comment]
@jwulf @tobyhede Thanks for waiting on us :)  We're almost to a beta for version 1 (maybe 1-2 weeks away).  At that point, we'd really appreciate your help.

**Comment by jwulf** [comment]
git clone the v1.0 branch, for example into `~/workspace`.

add something like this to `~/.bashrc` (or `~/.bash_profile` on a Mac):

`alias jaws-cli="~/workspace/JAWS/bin/jaws"`

Then do `source ~/.bashrc`.

Now you can do:
```
cd ~/workspace
jaws-cli new
```

This launches the wizard and creates a new project with scaffolding. Not much to see yet. There is a `jaws generate` command (to generate a lambda stub) described in the design doc, but it's not implemented yet.
